// Mocks generated by Mockito 5.4.6 from annotations
// in caloriecode/test/utils/test_data.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:caloriecode/models/food_code.dart' as _i2;
import 'package:caloriecode/models/product.dart' as _i5;
import 'package:caloriecode/models/scan_history_entry.dart' as _i8;
import 'package:caloriecode/repositories/scan_history_repository.dart' as _i7;
import 'package:caloriecode/services/food_code_service.dart' as _i6;
import 'package:caloriecode/services/product_data_service.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeFoodCode_0 extends _i1.SmartFake implements _i2.FoodCode {
  _FakeFoodCode_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ProductDataService].
///
/// See the documentation for Mockito's code generation for more information.
class MockProductDataService extends _i1.Mock
    implements _i3.ProductDataService {
  MockProductDataService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i5.Product?> fetchProduct(String? barcode) => (super.noSuchMethod(
        Invocation.method(
          #fetchProduct,
          [barcode],
        ),
        returnValue: _i4.Future<_i5.Product?>.value(),
      ) as _i4.Future<_i5.Product?>);
}

/// A class which mocks [FoodCodeService].
///
/// See the documentation for Mockito's code generation for more information.
class MockFoodCodeService extends _i1.Mock implements _i6.FoodCodeService {
  MockFoodCodeService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<void> saveFoodCode(_i2.FoodCode? code) => (super.noSuchMethod(
        Invocation.method(
          #saveFoodCode,
          [code],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<_i2.FoodCode?> getFoodCode(String? id) => (super.noSuchMethod(
        Invocation.method(
          #getFoodCode,
          [id],
        ),
        returnValue: _i4.Future<_i2.FoodCode?>.value(),
      ) as _i4.Future<_i2.FoodCode?>);

  @override
  _i4.Future<List<_i2.FoodCode>> getAllFoodCodes() => (super.noSuchMethod(
        Invocation.method(
          #getAllFoodCodes,
          [],
        ),
        returnValue: _i4.Future<List<_i2.FoodCode>>.value(<_i2.FoodCode>[]),
      ) as _i4.Future<List<_i2.FoodCode>>);

  @override
  _i4.Future<void> deleteFoodCode(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteFoodCode,
          [id],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i2.FoodCode createCustomCode(_i2.FoodCode? from) => (super.noSuchMethod(
        Invocation.method(
          #createCustomCode,
          [from],
        ),
        returnValue: _FakeFoodCode_0(
          this,
          Invocation.method(
            #createCustomCode,
            [from],
          ),
        ),
      ) as _i2.FoodCode);

  @override
  _i4.Future<_i2.FoodCode?> getActiveCode() => (super.noSuchMethod(
        Invocation.method(
          #getActiveCode,
          [],
        ),
        returnValue: _i4.Future<_i2.FoodCode?>.value(),
      ) as _i4.Future<_i2.FoodCode?>);

  @override
  _i4.Future<void> setActiveCode(String? id) => (super.noSuchMethod(
        Invocation.method(
          #setActiveCode,
          [id],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  List<_i2.FoodCode> getStarterCodes() => (super.noSuchMethod(
        Invocation.method(
          #getStarterCodes,
          [],
        ),
        returnValue: <_i2.FoodCode>[],
      ) as List<_i2.FoodCode>);
}

/// A class which mocks [ScanHistoryRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockScanHistoryRepository extends _i1.Mock
    implements _i7.ScanHistoryRepository {
  MockScanHistoryRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i8.ScanHistoryEntry>> getRecentScans({int? limit = 50}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRecentScans,
          [],
          {#limit: limit},
        ),
        returnValue: _i4.Future<List<_i8.ScanHistoryEntry>>.value(
            <_i8.ScanHistoryEntry>[]),
      ) as _i4.Future<List<_i8.ScanHistoryEntry>>);

  @override
  _i4.Future<void> addScan(_i8.ScanHistoryEntry? entry) => (super.noSuchMethod(
        Invocation.method(
          #addScan,
          [entry],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> clearHistory() => (super.noSuchMethod(
        Invocation.method(
          #clearHistory,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}
